openai-key: "REPLACE_ME"
model: omni-moderation-latest
threshold: 0.5
punishments:
  first: 5
  second: 30
  third: 1440
  fourth: 10080
blocked-categories:
  - harassment
  - hate
  - sexual
rate-limit: 60
use-blocked-words: true
blocked-words:
  - amk
  - orospu
  - pic
  - sik
  - yarak
  - got
  - amina
