openai-key: "REPLACE_ME"
language: en
model: omni-moderation-latest
threshold: 0.5
punishments:
  first: 5
  second: 30
  third: 60
  fourth: 180
blocked-categories:
  - harassment
  - harassment/threatening
  - hate
  - hate/threatening
  - illicit
  - illicit/violent
  - self-harm
  - self-harm/intent
  - self-harm/instructions
  - sexual
  - sexual/minors
  - violence
  - violence/graphic
category-settings:
  harassment:
    enabled: true
    ratio: 0.06
  harassment/threatening:
    enabled: true
    ratio: 0.06
  hate:
    enabled: true
    ratio: 0.06
  hate/threatening:
    enabled: true
    ratio: 0.06
  illicit:
    enabled: false
    ratio: 0.5
  illicit/violent:
    enabled: false
    ratio: 0.5
  self-harm:
    enabled: false
    ratio: 0.5
  self-harm/intent:
    enabled: false
    ratio: 0.5
  self-harm/instructions:
    enabled: false
    ratio: 0.5
  sexual:
    enabled: true
    ratio: 0.03
  sexual/minors:
    enabled: true
    ratio: 0.03
  violence:
    enabled: false
    ratio: 0.05
  violence/graphic:
    enabled: false
    ratio: 0.05
rate-limit: 250
debug: false
countdown-offline: true
use-blocked-categories: true
use-blocked-words: false
blocked-words:
  - amk
  - orospu
  - pic
  - sik
  - yarak
  - got
