openai-key: "REPLACE_ME"
language: en
model: omni-moderation-latest
threshold: 0.5
punishments:
  first: 5
  second: 30
  third: 60
  fourth: 180
blocked-categories:
  - harassment
  - harassment/threatening
  - hate
  - hate/threatening
  - illicit
  - illicit/violent
  - self-harm
  - self-harm/intent
  - self-harm/instructions
  - sexual
  - sexual/minors
  - violence
  - violence/graphic
rate-limit: 250
debug: false
countdown-offline: true
use-blocked-categories: true
use-blocked-words: true
use-category-thresholds: false
category-thresholds:
  harassment: 0.5
  harassment/threatening: 0.5
  hate: 0.5
  hate/threatening: 0.5
  illicit: 0.5
  illicit/violent: 0.5
  self-harm: 0.5
  self-harm/intent: 0.5
  self-harm/instructions: 0.5
  sexual: 0.5
  sexual/minors: 0.5
  violence: 0.5
  violence/graphic: 0.5
blocked-words:
  - amk
  - orospu
  - pic
  - sik
  - yarak
  - got
