openai-key: "REPLACE_ME"
language: en
model: omni-moderation-latest
threshold: 0.5
punishments:
  first: 5
  second: 30
  third: 60
  fourth: 180
blocked-categories:
  - harassment
  - harassment/threatening
  - hate
  - hate/threatening
  - illicit
  - illicit/violent
  - self-harm
  - self-harm/intent
  - self-harm/instructions
  - sexual
  - sexual/minors
  - violence
  - violence/graphic
rate-limit: 60
debug: false
use-blocked-words: true
blocked-words:
  - amk
  - orospu
  - pic
  - sik
  - yarak
  - got
  - amina
