openai-key: "REPLACE_ME"
language: en
# Set to `gpt-4.1-mini` to use the chat model with a profanity check prompt
model: omni-moderation-latest
# Prompt used by the chat model
chat-prompt: |-
  • Bir Minecraft sunucusu sohbetindeki TEK bir mesajı denetleyeceksin.
  • İstediğimiz tek çıktı: **VAR** (kural ihlali var) veya **YOK** (kural ihlali yok).
  • Ek açıklama YALNIZCA “VAR” çıktığında, kısa ve öz bir sebep olarak verilecek (örn. “ırkçı hakaret”, “cinsel şiddet tehdidi”).

  KURALLAR
  1. **“VAR”** yazılacak durumlar
     a. Hakaret/tehdit ► ağır küfür, doğrudan aşağılama, ölüm-yaralama vb. açık tehditler
     b. Nefret söylemi ► ırk, etnik köken, din, cinsiyet, cinsel yönelim, engellilik vb. hedef alan aşağılayıcı ifadeler
     c. Şiddet çağrısı ► “kesin şunu”, “öldür onları” gibi doğrudan ya da ciddi şiddet teşviki
     d. Cinsel saldırı ► tecavüz, taciz, grooming içerikli ifadeler
  2. **“YOK”** yazılacak durumlar
     • Oyun dili / rekabetçi kızıştırma: “noob”, “lan”, “bittin”, “altıma sıçtım”, “öldüm gülmekten”
     • Hafif argo / espirili beddua: “başına taş düşsün”, “dık” eki gibi zararsız kelime parçaları
     • Anlamı belirsiz veya bağlam gereği zararsız cümleler
  3. ÖZELLİKLER
     • Sansürlü/kısaltılmış küfürleri (f*k, s*ktir) tanı; gerekiyorsa “VAR” de.
     • Sadece mesajın içeriğine bak; önceki-sonraki iletileri, gönderen kimliğini vb. dikkate alma.
     • Çıktı kesinlikle büyük harf ve tırnaksız olacak: **VAR** ya da **YOK**
  ÖRNEKLER:
  oradan taşın dık” YOK
  “öldürürüm seni oğlum” VAR – tehdit
  “a^2na'ı s2^ker^2im” VAR – ailevi hakaret
  “öldüm lan LOL” YOK
  “Orospu Çocuğu” VAR – ağır küfür/ailevi küfür
  “noob team” YOK

  Kullanıcının Mesajı:
threshold: 0.5
punishments:
  first: 5
  second: 30
  third: 60
  fourth: 180
blocked-categories:
  - harassment
  - harassment/threatening
  - hate
  - hate/threatening
  - illicit
  - illicit/violent
  - self-harm
  - self-harm/intent
  - self-harm/instructions
  - sexual
  - sexual/minors
  - violence
  - violence/graphic
category-settings:
  harassment:
    enabled: true
    ratio: 0.5
  harassment/threatening:
    enabled: true
    ratio: 0.5
  hate:
    enabled: true
    ratio: 0.5
  hate/threatening:
    enabled: true
    ratio: 0.5
  illicit:
    enabled: false
    ratio: 0.5
  illicit/violent:
    enabled: false
    ratio: 0.5
  self-harm:
    enabled: false
    ratio: 0.5
  self-harm/intent:
    enabled: false
    ratio: 0.5
  self-harm/instructions:
    enabled: false
    ratio: 0.5
  sexual:
    enabled: true
    ratio: 0.5
  sexual/minors:
    enabled: true
    ratio: 0.5
  violence:
    enabled: false
    ratio: 0.5
  violence/graphic:
    enabled: false
    ratio: 0.5
rate-limit: 250
debug: false
countdown-offline: true
use-blocked-categories: true
use-blocked-words: FALSE
blocked-words:
  - amk
  - orospu
  - pic
  - sik
  - yarak
  - got
