openai-key: "REPLACE_ME"
language: en
# Set to 'gpt-4.1-mini', 'gpt-4.1', 'o3' or 'o4-mini' to use the chat model with a profanity check prompt
model: omni-moderation-latest
# Prompt used by the chat model
chat-prompt: "You are a Minecraft chat moderator. Evaluate one incoming message for inappropriate content: if it contains strong profanity, insults, hate speech, sexual slurs, religious or racial degradation, or threats, reply exactly “var”; otherwise reply exactly “yok”. Players may hide profanity with symbols, leetspeak (a→4, e→3, i→1, etc.), or by merging words—try to detect these. Ignore mild slang such as “lan”, “oha”, “salak”, “noob”, player nicknames, and Minecraft commands. Output must be all lowercase and contain nothing except either “var” or “yok”."
thinking-effort: medium
threshold: 0.5
punishments:
  first: 5
  second: 30
  third: 60
  fourth: 180
blocked-categories:
  - harassment
  - harassment/threatening
  - hate
  - hate/threatening
  - illicit
  - illicit/violent
  - self-harm
  - self-harm/intent
  - self-harm/instructions
  - sexual
  - sexual/minors
  - violence
  - violence/graphic
category-settings:
  harassment:
    enabled: true
    ratio: 0.5
  harassment/threatening:
    enabled: true
    ratio: 0.5
  hate:
    enabled: true
    ratio: 0.5
  hate/threatening:
    enabled: true
    ratio: 0.5
  illicit:
    enabled: false
    ratio: 0.5
  illicit/violent:
    enabled: false
    ratio: 0.5
  self-harm:
    enabled: false
    ratio: 0.5
  self-harm/intent:
    enabled: false
    ratio: 0.5
  self-harm/instructions:
    enabled: false
    ratio: 0.5
  sexual:
    enabled: true
    ratio: 0.5
  sexual/minors:
    enabled: true
    ratio: 0.5
  violence:
    enabled: false
    ratio: 0.5
  violence/graphic:
    enabled: false
    ratio: 0.5
rate-limit: 250
debug: false
countdown-offline: true
use-blocked-categories: true
use-blocked-words: FALSE
blocked-words:
  - amk
  - orospu
  - pic
  - sik
  - yarak
  - got
