openai-key: "REPLACE_ME"
language: en
# Set to 'gpt-4.1-mini', 'gpt-4.1', 'o3' or 'o4-mini' to use the chat model with a profanity check prompt
model: omni-moderation-latest
# Prompt used by the chat model
chat-prompt: "Sen minecraft sohbet moderatörüsün. Görevin Türkçe cümlede küfür veya hakaret varsa sadece var yoksa yok yaz (lan, altıma sıçtım gibi basit argo kelimeleri ve lezyiyen gibi nicknameleri ve minecraft sunucularında kullanılan terimleri görmezden gel sadece kullanıcıların birbirlerine doğrudan küfür ve hakaret emlerine izin vermeyeceksin) (kullanıcı küfürü gizlemek için özel karakterler veya sansürler kullanmış olabilir dikkat et):"
thinking-effort: medium
threshold: 0.5
punishments:
  first: 5
  second: 30
  third: 60
  fourth: 180
blocked-categories:
  - harassment
  - harassment/threatening
  - hate
  - hate/threatening
  - illicit
  - illicit/violent
  - self-harm
  - self-harm/intent
  - self-harm/instructions
  - sexual
  - sexual/minors
  - violence
  - violence/graphic
category-settings:
  harassment:
    enabled: true
    ratio: 0.5
  harassment/threatening:
    enabled: true
    ratio: 0.5
  hate:
    enabled: true
    ratio: 0.5
  hate/threatening:
    enabled: true
    ratio: 0.5
  illicit:
    enabled: false
    ratio: 0.5
  illicit/violent:
    enabled: false
    ratio: 0.5
  self-harm:
    enabled: false
    ratio: 0.5
  self-harm/intent:
    enabled: false
    ratio: 0.5
  self-harm/instructions:
    enabled: false
    ratio: 0.5
  sexual:
    enabled: true
    ratio: 0.5
  sexual/minors:
    enabled: true
    ratio: 0.5
  violence:
    enabled: false
    ratio: 0.5
  violence/graphic:
    enabled: false
    ratio: 0.5
rate-limit: 250
moderation-cache-minutes: 5
debug: false
discord-url: "http://localhost:3000"
web-port: 8081
unmute-threads: 10
http-connect-timeout: 10
http-read-timeout: 10
http-max-requests: 100
http-max-requests-per-host: 100
countdown-offline: true
max-log-entries: 1000
save-interval-ticks: 100
use-blocked-categories: true
# When true, messages are scanned against the blocked-words list before using the API
use-blocked-words: true
blocked-word-distance: 1
blocked-words:
  - amk
  - orospu
  - pic
  - sik
  - yarak
  - got
