name: ChatModeration
version: 0.1.0
main: me.ogulcan.chatmod.Main
author: ogulcan
api-version: "1.21"
commands:
  cm:
    permission: chatmoderation.command
permissions:
  chatmoderation.command:
    description: Allows moderation commands
    default: op
  chatmoderation.notify:
    description: Receive moderation notifications
    default: op
  chatmoderation.gui:
    description: Open the moderation GUI
    default: op
  chatmoderation.admin:
    description: Perform admin actions in the GUI
    default: op
